### ISSUE TITLE
Preprocess of Cora Dataset 

### ISSUE THREAD

**Issue by erinchen824** [bywmm/Bi-GCN#1]
Hi, there, could you please provide de preprocessing code for Cora dataset? 
I am just trying to test the code while the directly downloaded Cora dataset isn't working. 
Thanks!

**Comment by lw0210** [comment]
Hello, have you solved your problem？ @erinchen824

**Comment by bywmm** [comment]
Sorry for the late reply. We did not locate the cause of this problem. It seems to be related to the version of some packages.

You can manually download the raw data from this URL: 
https://github.com/kimiyoung/planetoid/tree/master/data. 

We have added the raw data of cora, which is also downloaded from the above URL. Hope this will help you.

**Comment by lw0210** [comment]
Thank you for your reply！I have&nbsp; resolved it.&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "bywmm/Bi-GCN"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Apr 20, 2023 05:14 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [bywmm/Bi-GCN] Preprocess of Cora Dataset  (#1)





 
Sorry for the late reply. We did not locate the cause of this problem. It seems to be related to the version of some packages.
 
You can manually download the raw data from this URL:
 https://github.com/kimiyoung/planetoid/tree/master/data.
 
We have added the raw data of cora, which is also downloaded from the above URL. Hope this will help you.
